I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 561, in script
    $ player_has_ribbon = false
  File "game/script.rpy", line 561, in <module>
    $ player_has_ribbon = false
NameError: name 'false' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 561, in script
    $ player_has_ribbon = false
  File "C:\Users\Parker Pawn\Downloads\renpy-8.1.3-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Parker Pawn\Downloads\renpy-8.1.3-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 561, in <module>
    $ player_has_ribbon = false
NameError: name 'false' is not defined

Windows-10-10.0.22631 AMD64
Ren'Py 8.1.3.23091805
Fantasy Ren'py GUI template 1.0
Sat Nov  4 19:50:30 2023
